CREATE TABLE evento(
	idevento BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(30) NOT NULL,
	descricao VARCHAR(100) NOT NULL,
	data DATE NOT NULL,
	tipo VARCHAR(20) NOT NULL

)ENGINE=InnoDB DEFAULT CHARSET=utf8;