CREATE TABLE usuario(
	idusuario BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(30) NOT NULL,
	senha VARCHAR(30) NOT NULL,
	datanascimento DATE NOT NULL

)ENGINE=InnoDB DEFAULT CHARSET=utf8;